### ISSUE TITLE
'FNQR' does not name a type

### ISSUE THREAD

**Issue by eggcob** [Freenove/Freenove_Quadruped_Robot_Kit#1]
Hi!

When I upload Example > FNQG > default > Robot:

Arduino: 1.8.5 (Windows 7), Board: "Arduino Mini, ATmega328P"

Robot:17: error: 'FNQR' does not name a type

 FNQR robot;

 ^

C:\Users\User\Documents\Arduino\Robot\Robot.ino: In function 'void setup()':

Robot:21: error: 'robot' was not declared in this scope

   robot.Start(true);

   ^

C:\Users\User\Documents\Arduino\Robot\Robot.ino: In function 'void loop()':

Robot:26: error: 'robot' was not declared in this scope

   robot.Update();

   ^

exit status 1
'FNQR' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by EthanPal** [comment]
Hi,
You met this problem due to you chose the wrong board.
This sketch only works on Arduino Mega 2560 board or boards based on it.
Please select "Arduino/Genuino Mega or Mega 2560" and try again.

**Comment by eggcob** [comment]
That was the issue! Many thanks :)

**Comment by EthanPal** [comment]
You are welcome!
