### ISSUE TITLE
Help!! :)

### ISSUE THREAD

**Issue by DemOnJR** [Freenove/Freenove_Quadruped_Robot_Kit#3]
guys i do not understand how is working when i turn on the power the robot begins to tremble i follow all steps you have a video tutorial or something else?
or i give you my teamview if you need to check something ...

**Comment by EthanPal** [comment]
Hi, usually this problem is caused by the wrong battery.
Please send our support team some pictures of your battery and a short video.
You can find the email address on the card in the box.

**Comment by DemOnJR** [comment]
ok, i buy another battery this https://www.amazon.it/gp/product/B07BLP31BS/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1 is ok?

**Comment by EthanPal** [comment]
Yes, NITECORE NL147 is good. We have tested it.
We received feedbacks from customers said sellers shipped them NL1485 instead of NL147.
NL1485 won't work. Please check once you get the battery.

**Comment by DemOnJR** [comment]
ok
