### ISSUE TITLE
Cannot find a class or type named “ControlRobot”

### ISSUE THREAD

**Issue by VegetarianSpoon** [Freenove/Freenove_Quadruped_Robot_Kit#4]
when i start it it makes this

**Comment by EthanPal** [comment]
Hi, did you use the latest Processing IDE to open this code?
Please post a picture of it.

**Comment by VegetarianSpoon** [comment]
processing 3.4
Cannot find a class or type named “ControlRobot”
ControlRobot controlRobot = new ControlRobot(this);

**Comment by VegetarianSpoon** [comment]
i don have the 3,7 v batteries i got 1,4 i think

**Comment by EthanPal** [comment]
Hi, I just tried the Processing 3.4. It works fine.
Please note there are other files in the folder, they are also indispensable.
![tim 20180827094013](https://user-images.githubusercontent.com/11417304/44636241-4b3dad80-a9dd-11e8-9619-c43b0e92f291.png)
If you don't miss any file, please send a picture of your screen.

**Comment by EthanPal** [comment]
You must use the 3.7V batteries to make the robot work.
The Processing APP will be opened even you don't use the right battery.
There is a file named "AboutBattery.pdf" to show you how to choose the right battery.

**Comment by VegetarianSpoon** [comment]
Doing this in an raspberry pi on raspbarian newest version still ok?

**Comment by VegetarianSpoon** [comment]
So i need to open all pde files

**Comment by EthanPal** [comment]
Yes, the Processing will work on Raspberry Pi with newest version Raspbian system.

**Comment by EthanPal** [comment]
You just need to open any one of the .pde file.
All the other .pde files in this folder will be opened automatically.
Please send a picture of your Processing IDE after you open the .pde file.

**Comment by VegetarianSpoon** [comment]
I Cant download them just copy and paste

**Comment by EthanPal** [comment]
I think this is the reason caused your problem.
You can download the code to your Raspberry Pi by running the following command in terminal:
git clone https://github.com/Freenove/Freenove_Quadruped_Robot_Kit
