### ISSUE TITLE
how do i fix this error

### ISSUE THREAD

**Issue by munchkin11** [Freenove/Freenove_Quadruped_Robot_Kit#5]
Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Users\Hanna\Documents\Arduino\libraries\RF24\RF24.cpp: In function 'powerUp.constprop':

C:\Users\Hanna\Documents\Arduino\libraries\RF24\RF24.cpp:777:1: internal compiler error: Segmentation fault

 }

 ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.15.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.15.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
In file included from C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRComm.h:13:0,

                 from C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQR.h:19,

                 from C:\Users\Hanna\Documents\Arduino\libraries\FNQR\examples\Default\Robot\Robot.ino:15:

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:21:26: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotShape::a' of non-integral type [-fpermissive]

   static const float a = 35;

                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:22:26: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotShape::b' of non-integral type [-fpermissive]

   static const float b = 35;

                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:23:26: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotShape::c' of non-integral type [-fpermissive]

   static const float c = 15.75;

                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:24:26: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotShape::d' of non-integral type [-fpermissive]

   static const float d = 22.75;

                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:25:26: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotShape::e' of non-integral type [-fpermissive]

   static const float e = 55;

                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:26:26: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotShape::f' of non-integral type [-fpermissive]

   static const float f = 70;

                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:32:42: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::controllerVersion' of non-integral type [-fpermissive]

   static const float controllerVersion = 0;

                                          ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:34:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo22' of non-integral type [-fpermissive]

   static const float servo22 = 10;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:35:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo23' of non-integral type [-fpermissive]

   static const float servo23 = 12;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:36:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo24' of non-integral type [-fpermissive]

   static const float servo24 = 14;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:37:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo25' of non-integral type [-fpermissive]

   static const float servo25 = 16;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:38:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo26' of non-integral type [-fpermissive]

   static const float servo26 = 18;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:39:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo27' of non-integral type [-fpermissive]

   static const float servo27 = 20;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:40:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo39' of non-integral type [-fpermissive]

   static const float servo39 = 22;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:41:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo38' of non-integral type [-fpermissive]

   static const float servo38 = 24;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:42:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo37' of non-integral type [-fpermissive]

   static const float servo37 = 26;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:43:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo36' of non-integral type [-fpermissive]

   static const float servo36 = 28;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:44:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo35' of non-integral type [-fpermissive]

   static const float servo35 = 30;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:45:32: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::servo34' of non-integral type [-fpermissive]

   static const float servo34 = 32;

                                ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:47:35: warning: 'constexpr' needed for in-class initialization of static data member 'const float EepromAddresses::robotState' of non-integral type [-fpermissive]

   static const float robotState = 50;

                                   ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:174:43: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotLeg::negligibleDistance' of non-integral type [-fpermissive]

   static const float negligibleDistance = 0.1;

                                           ^

C:\Users\Hanna\Documents\Arduino\libraries\FNQR/FNQRBasic.h:175:44: warning: 'constexpr' needed for in-class initialization of static data member 'const float RobotLeg::defaultStepDistance' of non-integral type [-fpermissive]

   static const float defaultStepDistance = 2;

                                            ^

C:\Users\Hanna\Documents\Arduino\libraries\RF24\RF24.cpp: In function 'powerUp.constprop':

C:\Users\Hanna\Documents\Arduino\libraries\RF24\RF24.cpp:777:1: internal compiler error: Segmentation fault

 }

 ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.15.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.15.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by EthanPal** [comment]
Hi, it seems that you are using a Windows Store app. There may be some problems with its compilation.
Please use an installed version of Arduino IDE and try again.

**Comment by per1234** [comment]
This bug is specific to the avr-gcc 5.4.0 used by Arduino AVR Boards 1.6.22 and newer. The issue report is here:
https://github.com/arduino/Arduino/issues/7949

The workaround is to roll back Arduino AVR Boards to 1.6.21:

1. Tools > Board > Boards Manager
2. Wait for downloads to finish.
3. Click on "Arduino AVR Boards".
4. Select 1.6.21 from the dropdown menu.
5. Click "Install".
6. Wait for installation to finish.
7. Click "Close".

Due to a [bug](https://github.com/arduino/Arduino/issues/7973), you can not do this with Arduino IDE 1.8.6 but you can with any other Arduino IDE version.

If you have **File > Check for updates on startup** enabled, the Arduino IDE will periodically prompt you to update Arduino AVR Boards. You must refrain from doing so, otherwise the error will come back.

**Comment by EthanPal** [comment]
We have also encountered such problems recently. Especially when there's a lot of code.
But when you click again, it's probably normal.
It looks like a bug.

**Comment by per1234** [comment]
I don't think it's a bug in this repository's code, but rather a bug in the compiler used by the Arduino IDE.

My experience has been that the bug is very sporadic and it sounds like you've found the same. So I don't know that it would be feasible to find a workaround by changing any of the code in this repository.

**Comment by EthanPal** [comment]
Yes, what I mean is that it seems a bug in the compiler too.
The repository should be good. Never met this problem when using old IDEs.
