### ISSUE TITLE
Failing to connect the control pad to the ProcessingApp (Via USB cable)

### ISSUE THREAD

**Issue by edenoftheabyss** [Freenove/Freenove_Quadruped_Robot_Kit#7]
I'm having trouble connecting the robot to the Processing software, I have done the tests and know there isn't any issues with the USB cable or anything similar. IT says 'Processing...' and then goes back to 'connect'. I have tried re-downloading the software and the sketch, however nothing has helped. I was wondering if there is anything else i can try, or at least an insight on what the problem may be.

**Comment by EthanPal** [comment]
Hi! Please don't worry. We will help you with it.
Please click the CONNECT button, then send me the full message on the bottom of the Processing IDE.

**Comment by edenoftheabyss** [comment]
12:2:15 Serial detected: COM3
12:2:15 Serial connection attempt: COM3...
12:2:17 Serial read failed: time out 
12:2:17 Serial connection failed: detected serial, no serial responded

hope that what you wanted.

**Comment by EthanPal** [comment]
Yes, thank you! 
The port of the control board is COM3 on Arduino IDE, right?
If it is, then this problem should be caused by not uploading default sketch to the control board.
Please upload default sketch to the control board and then try again.

**Comment by edenoftheabyss** [comment]
Will do. Thanks a lot!

**Comment by EthanPal** [comment]
You are welcome!
Please feel free to contact us again if you need any further help.

**Comment by edenoftheabyss** [comment]
I'm really sorry, this is my first time using the software, and I'm still really confused. I'm pretty certain the default sketch is running, and I'm still getting the same error message. Is there anything else it could be?

**Comment by EthanPal** [comment]
Don't worry. We will help you until any issues are resolved.
In a few cases, some unexpected problems do occur. We also need to collect more information to help you.
Please confirm the following:
1. Do not connect the USB cable and then open the power of the robot. How does the LED L on the control board flash?
2. Connect the robot to the computer, what is the Port displayed by the Arduino IDE? A picture of it will be perfect.

**Comment by edenoftheabyss** [comment]
Sorry I didn't notice the message sooner. Fortunately I figured out the issue, it turns out that I hadn't uploaded the sketch on Arduino properly. Thank you so much for your help though, and quick responses. :)

**Comment by EthanPal** [comment]
I am very glad that your problem has been resolved.
Please feel free to contact us again if there is anything we can do for you!
